version: 0.0
os: linux
files:
  - source: /
    destination: /opt
hooks:
  BeforeInstall:
    - location: scripts/clear_directory.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_project.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
